apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  labels:
    app: springOAuth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springOAuth2
  template:
    metadata:
      labels:
        app: springOAuth2
    spec:
      containers:
        - name: springOAuth2
          image: sriharipriya/springOAuth2:${{ github.run_number }}

          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springOAuth2-loadbalancer-service
  labels:
    app: springOAuth2
spec:
  type: LoadBalancer
  selector:
    app: springOAuth2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
